spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-94.railway.app:6026/railway
    username: postgres
    password: b4ETTyTk9nqkeqykAcyZ
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

